### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by zcablii** [zhu-xlab/FGMAE#1]
Your work is great! And we would like to follow along. However, I'm encountering difficulties installing the environment, particularly with the 'cvtorchvision' package. Could you kindly provide guidance on how to install this package?

**Comment by wangyi111** [comment]
Thanks! For this package we installed with `pip install opencv-torchvision-transforms-yuzhiyang`, following https://github.com/hityzy1122/opencv_transforms_torchvision. This package is to simply make torchvision transforms applicable to multispectral data. You could also use [kornia](https://github.com/kornia/kornia) for this purpose and more functions.
